# Compute a stable fingerprint over an EDL file, its transitive `from`
# imports, and direct C headers included by those EDL files. Absolute
# source/install paths are excluded so the same contract has the same
# identity in build and staging prefixes.
function(fid_compute_edl_fingerprint output root_edl)
  if(NOT EXISTS "${root_edl}")
    message(FATAL_ERROR "EDL contract root does not exist: ${root_edl}")
  endif()

  get_filename_component(root_directory "${root_edl}" DIRECTORY)
  set(search_directories "${root_directory}")
  foreach(raw_path ${ARGN})
    string(REPLACE ":" ";" expanded_paths "${raw_path}")
    list(APPEND search_directories ${expanded_paths})
  endforeach()
  if(SGX_INCLUDE_DIR)
    list(APPEND search_directories "${SGX_INCLUDE_DIR}")
  endif()
  if(SGX_PATH)
    list(APPEND search_directories "${SGX_PATH}/include")
  endif()
  list(REMOVE_DUPLICATES search_directories)

  set(queue "${root_edl}")
  set(visited)
  set(visited_headers)
  set(contract_records "")
  while(NOT "${queue}" STREQUAL "")
    list(GET queue 0 current_edl)
    list(REMOVE_AT queue 0)
    get_filename_component(current_edl "${current_edl}" REALPATH)
    list(FIND visited "${current_edl}" visited_index)
    if(NOT visited_index EQUAL -1)
      continue()
    endif()
    list(APPEND visited "${current_edl}")

    file(SHA256 "${current_edl}" current_sha256)
    get_filename_component(current_name "${current_edl}" NAME)
    string(APPEND contract_records "${current_name}:${current_sha256}\n")
    file(READ "${current_edl}" current_text)
    string(REGEX MATCHALL "from[ \t\r\n]+\"[^\"]+\""
           import_statements "${current_text}")
    get_filename_component(current_directory "${current_edl}" DIRECTORY)
    foreach(import_statement ${import_statements})
      string(REGEX REPLACE ".*\"([^\"]+)\".*" "\\1" import_name
             "${import_statement}")
      set(import_file "")
      if(IS_ABSOLUTE "${import_name}" AND EXISTS "${import_name}")
        set(import_file "${import_name}")
      elseif(EXISTS "${current_directory}/${import_name}")
        set(import_file "${current_directory}/${import_name}")
      else()
        foreach(search_directory ${search_directories})
          if(EXISTS "${search_directory}/${import_name}")
            set(import_file "${search_directory}/${import_name}")
            break()
          endif()
        endforeach()
      endif()
      if(import_file STREQUAL "")
        message(FATAL_ERROR
          "Cannot resolve EDL import '${import_name}' from ${current_edl}")
      endif()
      list(APPEND queue "${import_file}")
    endforeach()

    string(REGEX MATCHALL "include[ \t\r\n]+\"[^\"]+\""
           include_statements "${current_text}")
    foreach(include_statement ${include_statements})
      string(REGEX REPLACE ".*\"([^\"]+)\".*" "\\1" include_name
             "${include_statement}")
      set(include_file "")
      if(IS_ABSOLUTE "${include_name}" AND EXISTS "${include_name}")
        set(include_file "${include_name}")
      elseif(EXISTS "${current_directory}/${include_name}")
        set(include_file "${current_directory}/${include_name}")
      else()
        foreach(search_directory ${search_directories})
          if(EXISTS "${search_directory}/${include_name}")
            set(include_file "${search_directory}/${include_name}")
            break()
          endif()
        endforeach()
      endif()
      if(include_file STREQUAL "")
        message(FATAL_ERROR
          "Cannot resolve EDL include ${include_name} from ${current_edl}")
      endif()
      get_filename_component(include_file "${include_file}" REALPATH)
      list(FIND visited_headers "${include_file}" header_index)
      if(header_index EQUAL -1)
        list(APPEND visited_headers "${include_file}")
        file(SHA256 "${include_file}" include_sha256)
        string(APPEND contract_records
          "include:${include_name}:${include_sha256}\n")
      endif()
    endforeach()
  endwhile()

  set(contract_dependencies ${visited} ${visited_headers})
  list(REMOVE_DUPLICATES contract_dependencies)
  if(NOT CMAKE_SCRIPT_MODE_FILE)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
      ${contract_dependencies})
  endif()

  string(SHA256 contract_fingerprint "${contract_records}")
  set(${output} "${contract_fingerprint}" PARENT_SCOPE)
  set(${output}_DEPENDENCIES "${contract_dependencies}" PARENT_SCOPE)
endfunction()
